// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLmr9sTYNwuiA9VihuoTVCd3yrJG3PWYA',
    appId: '1:607390341660:web:85beea2b8b5a3eb5715dd9',
    messagingSenderId: '607390341660',
    projectId: 'samanta-2aaa6',
    authDomain: 'samanta-2aaa6.firebaseapp.com',
    storageBucket: 'samanta-2aaa6.appspot.com',
    measurementId: 'G-144VN6M0XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdwp8EFOrM5Vho4OOe4ALfh7ByWMdntyE',
    appId: '1:607390341660:android:6c9474e33238f75b715dd9',
    messagingSenderId: '607390341660',
    projectId: 'samanta-2aaa6',
    storageBucket: 'samanta-2aaa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCisSAXt42sEVoALoUMseT-YXv9otQlnXk',
    appId: '1:607390341660:ios:07b74d1c79412bfa715dd9',
    messagingSenderId: '607390341660',
    projectId: 'samanta-2aaa6',
    storageBucket: 'samanta-2aaa6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCisSAXt42sEVoALoUMseT-YXv9otQlnXk',
    appId: '1:607390341660:ios:ad378b0613c18e51715dd9',
    messagingSenderId: '607390341660',
    projectId: 'samanta-2aaa6',
    storageBucket: 'samanta-2aaa6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
